steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'build',
        '-t', 'gcr.io/$PROJECT_ID/recruiter-agent',
        '--cache-from', 'gcr.io/$PROJECT_ID/recruiter-agent',
        '.'
      ]

images:
  - 'gcr.io/$PROJECT_ID/recruiter-agent'
